name: Build EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || echo "no requirements.txt"

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile main.py

      - name: List dist files
        run: dir dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: exe-output
          path: dist/*
